Modernize check_puppet_agent
This removes puppet 2-3 support (oh well!), adds shellcheck cleanup, and adds some parsing of the last-run yaml to find issues to report to nagios.

diff --git a/check_puppet_agent b/check_puppet_agent
--- a/check_puppet_agent
+++ b/check_puppet_agent
@@ -11,23 +11,14 @@
 #
 # CHANGELOG
 # 5/15/2013 bhourigan Initial commit
+# 6/27/2013 bhourigan Addressing bug 887439, looking at /var/lib/puppet/state/agent_catalog_run.lock
+#  2/3/2014 bhourigan Bug 967265 - not properly parsing multi-line YAML messages
 #
 
-# NOTE: Puppet 3.x changed configprint syntax
-puppetversion=$(puppet -V)
-case $puppetversion in
-   2.*)
-      statedir=$(puppet --configprint statedir)
-      ;;
-   3.*)
-      statedir=$(puppet config print statedir)
-      ;;
-   *)
-      echo "Sorry, puppet version ${puppetversion:-UNKNOWN} is unsupported by $0"
-      exit 1
-      ;;
-esac
+PATH=/usr/bin:/usr/sbin:/opt/puppetlabs/bin
 
+puppetversion=$(puppet -V)
+statedir=$(puppet config print statedir)
 statefile=${statedir}/last_run_summary.yaml
 reportfile=${statedir}/last_run_report.yaml
 disablefile=${statedir}/disabled.at
@@ -51,36 +42,59 @@ usage(){
 
 result(){
    echo "$1"
-   exit $2
+   exit "$2"
+}
+
+check_stale_lock_files(){
+   if [ -f /var/lib/puppet/state/agent_catalog_run.lock ]; then
+      age=$(date -d "now - $(stat -c "%Y" /var/lib/puppet/state/agent_catalog_run.lock) seconds" +%s)
+
+      if [ "${age:-0}" -gt "${threshold}" ]; then
+         result "Agent lockfile /var/lib/puppet/state/agent_catalog_run.lock ${age} seconds old" 3
+      fi
+   fi
+}
+
+check_catalog_version(){
+   if [ -z "$configuration_version" ]; then
+      echo "Catalog version is unknown"
+      exit 3
+   fi
 }
 
 check_last_run_time(){
-   if [ ! -f $disablefile ]; then
+   if [ ! -f "$disablefile" ]; then
       # Parse last_last run from statefile
-      last_run_time=$(awk '/\s*last_run:/ {print $2}' $statefile)
-      if [ ${last_run_time:-0} -eq 0 ]; then
+      last_run_time=$(awk '/\s*last_run:/ {print $2}' "$statefile")
+      if [ "${last_run_time:-0}" -eq 0 ]; then
          result "Can't get last_run from $statefile" 3
       fi
 
       now=$(date "+%s")
       time_since_last=$((now-last_run_time))
-      if [ $time_since_last -gt $threshold ]; then
+      if [ "$time_since_last" -gt "$threshold" ]; then
          result "Last run was ${time_since_last} seconds ago" 3
       fi
    else
-      comment=$(grep 'Puppet has been disabled' /etc/motd | sed -r "s/\x1B\[([0-9]{1,3}((;[0-9]{1,3})*)?)?[m|K]//g")
-      result "${comment}" 0
+      comment=$(grep 'Puppet has been disabled' /var/lib/puppetctl.status | sed -r "s/\x1B\[([0-9]{1,3}((;[0-9]{1,3})*)?)?[m|K]//g")
+      if [ -n "$comment" ]; then
+         # we return 0 because, if someone has actively disabled puppet,
+         # a human has control and thus it's not an alert.
+         result "${comment}" 0
+      else
+         result "Puppet appears disabled but has no valid comment as to why." 3
+      fi
    fi
 }
 
 check_last_run_errors(){
-   failed=$(awk '/\s*failed:/ {print $2}' $statefile)
-   failure=$(awk '/\s*failed:/ {print $2}' $statefile)
-   fail_to_restart=$(awk '/\s*failed:/ {print $2}' $statefile)
-   sum_of_fail=$((failed+failure+failure_to_restart))
+   failed=$(awk '/\s*failed:/ {print $2}' "$statefile")
+   failure=$(awk '/\s*failed:/ {print $2}' "$statefile")
+   fail_to_restart=$(awk '/\s*failed:/ {print $2}' "$statefile")
+   sum_of_fail=$((failed+failure+fail_to_restart))
 
-   if [ ${sum_of_fail:-0} -gt 0 ]; then
-      if [ ${sum_of_fail:-0} -gt 1 ]; then
+   if [ "${sum_of_fail:-0}" -gt 0 ]; then
+      if [ "${sum_of_fail:-0}" -gt 1 ]; then
          s="s"
       fi
       result "Last run had ${sum_of_fail} error${s:-}" 1
@@ -88,24 +102,51 @@ check_last_run_errors(){
 }
 
 check_catalog_compile(){
-   failed_catalog=$(awk -F '"' '/\s*Could not retrieve catalog from remote server:|\s*Failed to apply catalog/ {gsub(/on node .*/,"",$2); print $2}' $reportfile)
+   {
+      # We add /opt/puppetlabs/puppet/bin because we want access to
+      # the ruby binary (for parsing the last-run yaml), since trying to parse
+      # YAML in bash is insane.
+      PATH=/opt/puppetlabs/puppet/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
 
-   if [ ! -z "${failed_catalog:-}" ]; then
-      result "${failed_catalog}" 2
+      # see https://puppet.com/docs/puppet/latest/format_report.html for hints
+      # on how we go through the object from the YAML file.
+      # Loop through the logs, and print the first log at the 'err' level.
+      # Future caution: the failure message is presently always the first error.
+      # This might need better logic in the future.
+      failed_catalog=$(reportfile=$reportfile ruby -rpuppet -ryaml \
+      -e "output = File.open(ENV['reportfile']){ |data| YAML::load(data) }; \
+          for line in output.logs do \
+            next if line.level.to_s() != 'err'; \
+            puts line; \
+            break; \
+          end" 2>/dev/null)
+   }
+
+   # strip out string portion if contains secret
+   has_secret=$(echo "${failed_catalog}" | grep -c 'secret')
+   if [ "${has_secret}" -gt 0 ]; then
+      failed_catalog=${failed_catalog//.secret.*$/<redacted>}
+   fi
+
+   if [ -n "${failed_catalog:-}" ]; then
+      if [[ "${failed_catalog:-}" =~ "execution expired" ]]; then
+         result "${failed_catalog}" 3
+      else
+         result "${failed_catalog}" 2
+      fi
    fi
 }
 
 result_ok(){
-   configuration_version=$(awk -F '"' '/\s*configuration_version:/ {print $2}' $reportfile)
    result "Puppet agent ${puppetversion} running catalog ${configuration_version:-UNKNOWN}" 0
 }
 
-while getopts ":t:s:d:c" opt; do
+while getopts "t:s:d:r:c" opt; do
    case $opt in
       t)
          threshold=$OPTARG
          ;;
-      t)
+      s)
          statefile=$OPTARG
          ;;
       d)
@@ -126,11 +167,11 @@ while getopts ":t:s:d:c" opt; do
    esac
 done
 
-if [ ! -f $statefile ]; then
+if [ ! -f "$statefile" ]; then
    result "State file $statefile doesn't exist" 3
 fi
 
-if [ ! -f $reportfile ]; then
+if [ ! -f "$reportfile" ]; then
    result "Report file $reportfile doesn't exist" 3
 fi
 
@@ -139,20 +180,24 @@ fi
 # immediately, and run time errors daily), so this script will operate
 # in two modes which will be defined with two different notification
 # intervals in Nagios
+configuration_version=$(grep configuration_version "$reportfile" | cut -d ':' -f 2)
 
-if [ ${check_catalog:-0} -eq 1 ]; then
-   if [ ${threshold:-0} -gt 1 ]; then
+if [ "${check_catalog:-0}" -eq 1 ]; then
+   if [ "${threshold:-0}" -gt 1 ]; then
       usage "Threshold argument not allowed with -c"
    fi
 
    check_catalog_compile
+   check_catalog_version
 else
-   if [ ${threshold:-0} -lt 1 ]; then
+   if [ "${threshold:-0}" -lt 1 ]; then
       usage "Invalid time threshold $OPTARG"
    fi
 
+   check_stale_lock_files
    check_last_run_time
    check_last_run_errors
+   check_catalog_version
 fi
 
 result_ok
