Addressed some CLI parsing bugs Added a logging mechanism to audit usage and collect data for later analysis Various cosmetic enhancements

diff --git a/puppetctl b/puppetctl
--- a/puppetctl
+++ b/puppetctl
@@ -8,59 +8,120 @@
 #
 # Based on code by Marco Bonetti <marco.bonetti@slackware.it>
 #
-# 7/31/2012  Added some additional status info to 'puppetctl status' - bhourigan
-# 9/21/2012  Added a feature to quickly disable puppet for 1 hour when disable is invoked with no arguments
-# 9/24/2012  Fixed a bug where a sleeping puppet process could run after running 'puppetctl disable'
-# 11/7/2012  Added a check to see if disabled.at is 0 bytes (disk full) and alert user
-# 11/13/2012 Added a check to see if last_run_summary.yaml is incomplete, throwing an appropriate error message
-# 12/13/2012 Fixed a bug where it would erroneously detect invalid characters from ps when multiple puppet instances were running
-# 1/10/2013  Added posix time spec support, improved command line documentation
+# 07/31/2012  bhourigan   Added some additional status info to 'puppetctl status' - bhourigan
+# 09/21/2012  bhourigan   Added a feature to quickly disable puppet for 1 hour when disable is invoked with no arguments
+# 09/24/2012  bhourigan   Fixed a bug where a sleeping puppet process could run after running 'puppetctl disable'
+# 11/07/2012  bhourigan   Added a check to see if disabled.at is 0 bytes (disk full) and alert user
+# 11/13/2012  bhourigan   Added a check to see if last_run_summary.yaml is incomplete, throwing an appropriate error message
+# 12/13/2012  bhourigan   Fixed a bug where it would erroneously detect invalid characters from ps when multiple puppet instances were running
+# 01/10/2013  bhourigan   Added posix time spec support, improved command line documentation
+# 01/15/2013  bhourigan   Fixed two bugs parsing command line parameters, clarified an error message
+# 02/26/2013  bhourigan   Added logging to help diagnose difficult to troubleshoot bug reports
+# 02/27/2013  bhourigan   Added a cosmetic enhancement, cleaned up logging functions.
+# 03/06/2013  bhourigan   Attempting to address bug 830343 again
+# 03/12/2013  rsoderberg  Added DISABLE_EXPIRATION_TIME, use it in help text as well.
+# 03/19/2013  bhourigan   Colorized puppet 3.x notices, changed cron detection method from stdin tty to environment variable (thanks :atoll)
+
+DISABLE_EXPIRATION_TIME='now + 1 hour'
+PUPPET_AGENT_OPTIONS='--verbose --onetime --no-daemonize'
+
+log(){
+   if [ -z "$SUDO_USER" ]; then
+      logger -t "puppetctl" "$*"
+   else
+      logger -t "puppetctl[$SUDO_USER]" "$*"
+   fi
+}
+
+# log_print "message" $color
+log_print(){
+   log "$1"
+
+   if [ ! -z "$2" ] && [ -t 0 ]; then
+      echo -e "\033[${2}m${1}\033[0m"
+   else
+      if [ -t 0 ]; then
+         echo "$1"
+      else
+         echo "puppetctl: $1"
+      fi
+   fi
+
+   exit 1
+}
+
+# error_print "message" $color
+error_print(){
+   log_print "$1" "$2"
+   exit 1
+}
 
 enable(){
    sed -i.bak -e '/Puppet has been disabled by/d' /etc/motd
 
    if [ -f /var/lib/puppet/state/disabled.at ]; then
+      if [ -f /var/lib/puppet/state/disabled.at.job ]; then
+         atrm $(cat /var/lib/puppet/state/disabled.at.job)
+         rm -f /var/lib/puppet/state/disabled.at.job
+      fi
+
       rm -f /var/lib/puppet/state/disabled.at
-      echo "Puppet has been enabled"
+      log_print "Puppet has been enabled"
    else
-      echo "Puppet is already enabled"
+      log_print "Puppet is already enabled"
    fi
 }
 
 disable(){
+   full_args="puppetctl disable"
+
    until [ -z "$1" ]; do
       case "$1" in
          -m|--message)
+            if [ -z "$2" ]; then
+               error_print "missing argument to $1"
+            fi
+
+            full_args="$full_args $1 '${2//\'/\\\'}'"
             message="$2"
             shift 2
             ;;
          -t|--time)
+            if [ -z "$2" ]; then
+               error_print "missing argument to $1"
+            fi
+
+            full_args="$full_args $1 '${2//\'/\\\'}'"
             time="$2"
             shift 2
             ;;
          -T|--posixtime)
+            if [ -z "$2" ]; then
+               error_print "missing argument to $1"
+            fi
+
+            full_args="$full_args $1 '${2//\'/\\\'}'"
             time="$2"
             posix="-t"
             shift 2
             ;;
          -f|--force)
+            full_args="$full_args $1"
             force=1
             shift 1
             ;;
          *)
-            echo "Invalid option: $1"
-            exit 1
+            error_print "Invalid option: $1"
             ;;
       esac
    done
 
-   pid=$(ps auwwx | grep -i 'puppet agent' | grep -v 'grep\|/bin/sh' | awk '{print $2}')
+   pid=$(ps auwwx | grep -i 'puppet agent\|puppetd ' | grep -v 'grep\|/bin/sh' | awk '{print $2}')
    if [ ${force:-0} -gt 0 ]; then
       security=$(echo $pid | tr -d '[:digit:][:space:]')
 
       if [ ! -z "$security" ]; then
-         echo "WARNING: Extra characters detected in pid field from ps: \"$security\" (pid: $pid)"
-         exit 1
+         error_print "WARNING: Extra characters detected in pid field from ps: \"$security\" (pid: $pid)"
       fi
 
       if [ ! -z "$pid" ]; then
@@ -71,10 +132,12 @@ disable(){
             sleep 1
          done
          echo " killed."
+         log "Puppet already running as pid $pid, killed with -TERM"
       fi
    else
       if [ ! -z "$pid" ]; then
-         echo -e "\033[0;36mnotice: Run of Puppet configuration client already in progress; skipping (hint: puppetctl disable -f to kill the running process)\033[0m"
+         log_print "notice: Run of Puppet configuration client already in progress; skipping (hint: $full_args -f; to kill the running process)" "0;36"
+         ps auwwx | grep -i 'puppet agent\|puppetd ' | grep -v 'grep\|/bin/sh'
          exit 1
       fi
    fi
@@ -82,36 +145,21 @@ disable(){
 
    if [ -f /var/lib/puppet/state/disabled.at ]; then
       if [ ${force:-0} -eq 0 ]; then
-         echo "Puppet is already disabled:"
+         log_print "Puppet is already disabled (hint: $full_args -f; to override)"
          echo
          grep 'Puppet has been disabled' /etc/motd | sed -r "s/\x1B\[([0-9]{1,3}((;[0-9]{1,3})*)?)?[m|K]//g"
          exit 1
       else
+         if [ -f /var/lib/puppet/state/disabled.at.job ]; then
+            atrm $(cat /var/lib/puppet/state/disabled.at.job)
+            rm -f /var/lib/puppet/state/disabled.at.job
+         fi
          sed -i.bak -e '/Puppet has been disabled by/d' /etc/motd
       fi
    fi
 
-   if [ -z "$message" ]; then
-      if [ -z "$time" ]; then
-         time="now + 1 hour"
-      else
-         usage "missing message"
-      fi
-   fi
-
-   echo "sed -i.bak -e '/Puppet has been disabled by/d' /etc/motd" > /var/lib/puppet/state/disabled.at
-   echo "rm -f /var/lib/puppet/state/disabled.at" >> /var/lib/puppet/state/disabled.at
-   if [ ! -s /var/lib/puppet/state/disabled.at ]; then
-      rm -f /var/lib/puppet/state/disabled.at
-      echo -e "\033[1;31mDisk is full. Refusing to disable puppet.\033[0m"
-      exit 2
-   fi
-
-   output=$(at -f /var/lib/puppet/state/disabled.at ${posix:-} "$time" 2>&1)
-   if [ $? -ne 0 ]; then
-      rm -f /var/lib/puppet/state/disabled.at
-      echo "$output"
-      exit 1
+   if [ -z "$time" ]; then
+      time="${DISABLE_EXPIRATION_TIME}"
    fi
 
    if [ ! -z "$SUDO_USER" ]; then
@@ -120,11 +168,34 @@ disable(){
       invoking_user="$USER"
    fi
 
+   echo "logger -t \"puppetctl[$invoking_user]\" Puppet has been enabled on schedule" > /var/lib/puppet/state/disabled.at
+   echo "sed -i.bak -e '/Puppet has been disabled by/d' /etc/motd" >> /var/lib/puppet/state/disabled.at
+   echo "rm -f /var/lib/puppet/state/disabled.at" >> /var/lib/puppet/state/disabled.at
+   if [ ! -s /var/lib/puppet/state/disabled.at ]; then
+      rm -f /var/lib/puppet/state/disabled.at
+      error_print "Disk might be full. Can't write to /var/lib/puppet/state/disabled.at. Refusing to disable puppet." "1;31"
+   fi
+
+   output=$(at -f /var/lib/puppet/state/disabled.at ${posix:-} "$time" 2>&1)
+   status=$?
+   if [ $status -ne 0 ]; then
+      rm -f /var/lib/puppet/state/disabled.at
+      log_print "ERROR: at returned non-zero exit status $status"
+      echo
+      echo "$output"
+      exit 1
+   else
+      job=$(echo "$output" | sed -e 's/job \([[:digit:]]*\) at.*/\1/g')
+      if [ ! -z "$job" ]; then
+         echo $job > /var/lib/puppet/state/disabled.at.job
+      fi
+   fi
+
    real_time=$(echo "$output" | sed '/^job.*at */!d; s///;q')
    if [ -z "$message" ]; then
-      echo -e "\033[1;31mPuppet has been disabled by $invoking_user at $(date "+%Y-%m-%d %H:%M") until $real_time\033[0m" | tee -a /etc/motd
+      log_print "Puppet has been disabled by $invoking_user at $(date "+%Y-%m-%d %H:%M") until $real_time" "1;31" | tee -a /etc/motd
    else
-      echo -e "\033[1;31mPuppet has been disabled by $invoking_user at $(date "+%Y-%m-%d %H:%M") until $real_time with the following message: $message\033[0m" | tee -a /etc/motd
+      log_print "Puppet has been disabled by $invoking_user at $(date "+%Y-%m-%d %H:%M") until $real_time with the following message: $message" "1;31" | tee -a /etc/motd
    fi
 }
 
@@ -134,8 +205,7 @@ run(){
       security=$(echo $pid | tr -d '[:digit:]')
 
       if [ ! -z "$security" ]; then
-         echo "WARNING: Extra characters detected in pid field from ps: \"$security\" (pid: $pid)"
-         exit 1
+         error_print "WARNING: Extra characters detected in pid field from ps: \"$security\" (pid: $pid)"
       fi
 
       if [ ! -z "$pid" ]; then
@@ -144,22 +214,27 @@ run(){
          delta=$(expr $current - $age)
 
          if [ ! -z "$delta" ] && [ "$delta" -gt 3600 ]; then
-            echo "Killed hung puppet process, had been running for $delta seconds"
+            log_print "Killed hung puppet process, had been running for $delta seconds"
             kill -9 $pid
          fi
       fi
 
       puppet agent --enable
-      if [ -t 0 ]; then
-         puppet agent --verbose --onetime --no-daemonize --no-splay $@
+      if [ -t 0 ] || [ -z "$MAILTO" ]; then
+         if [ -x /usr/bin/stdbuf ]; then
+            puppet agent $PUPPET_AGENT_OPTIONS --no-splay $@ | stdbuf -o0 awk '/^[Nn]otice/ {print "\033[1;35m" $0 "\033[0m"; next} {print $0}'
+         else
+            puppet agent $PUPPET_AGENT_OPTIONS --no-splay $@
+         fi
       else
-	 puppet agent --verbose --onetime --no-daemonize $@
+	 puppet agent $PUPPET_AGENT_OPTIONS $@
       fi
    else
       if [ -t 0 ]; then
          grep -v '^[ 	]*#' /etc/cron.d/puppetcheck | grep -q 'puppet agent\|puppetctl'
+
          if [ $? -ne 0 ]; then
-            echo "Puppet has not been disabled with puppetctl, but it seems to be commented out in /etc/cron.d/puppetcheck. Not running puppet."
+            log_print "Puppet has not been disabled with puppetctl, but it seems to be commented out in /etc/cron.d/puppetcheck. Not running puppet."
          else
             grep 'Puppet has been disabled' /etc/motd | sed -r "s/\x1B\[([0-9]{1,3}((;[0-9]{1,3})*)?)?[m|K]//g"
          fi
@@ -180,25 +255,23 @@ status(){
                   errors=$(ruby -ryaml -e "output = File.open('/var/lib/puppet/state/last_run_summary.yaml'){ |data| YAML::load(data) }; puts output['resources']['failed']" 2>/dev/null)
 
                   if [ -z "$age" ] || [ -z "$errors" ]; then
-                     echo "Puppet is enabled, but /var/lib/puppet/state/last_run_summary.yaml is incomplete (puppet is broken)"
+                     log_print "Puppet is enabled, but /var/lib/puppet/state/last_run_summary.yaml is incomplete (puppet is broken)"
                   else
-                     echo "Puppet is enabled, last ran $(($age/3600))d $(($age%3600/60))m $(($age%60))s ago with $errors errors."
+                     log_print "Puppet is enabled, last ran $(($age/3600))d $(($age%3600/60))m $(($age%60))s ago with $errors errors."
                   fi
                else
-                  echo "Puppet is enabled"
+                  log_print "Puppet is enabled"
                fi
+
                exit 0
             else
-               echo "Puppet has not been disabled with puppetctl, but it seems /usr/bin/puppet is not set to be executable"
-               exit 1
+               error_print "Puppet has not been disabled with puppetctl, but it seems /usr/bin/puppet is not set to be executable"
             fi
          else
-            echo "Puppet has not been disabled with puppetctl, but puppet seems to be commented out in /etc/cron.d/puppetcheck"
-            exit 1
+            error_print "Puppet has not been disabled with puppetctl, but puppet seems to be commented out in /etc/cron.d/puppetcheck"
          fi
       else
-         echo "Puppet has not been disabled with puppetctl, but /etc/cron.d/puppetcheck seems to be missing"
-         exit 1
+         error_print "Puppet has not been disabled with puppetctl, but /etc/cron.d/puppetcheck seems to be missing"
       fi
    else
       grep 'Puppet has been disabled' /etc/motd | sed -r "s/\x1B\[([0-9]{1,3}((;[0-9]{1,3})*)?)?[m|K]//g"
@@ -227,14 +300,13 @@ usage() {
    echo
    echo "   disable"
    echo "      -t"
-   echo "      --time time"
+   echo "      --time 'at(1) timespec'"
    echo "         Set the disable expiration time using at(1) specification. Defaults"
-   echo "         to 1 hour"
+   echo "         to '${DISABLE_EXPIRATION_TIME}'"
    echo
    echo "      -T"
    echo "      --posixtime [[CC]YY]MMDDhhmm[.SS]"
-   echo "         Set the disable expiration time using POSIX time format. Defaults"
-   echo "         to 1 hour"
+   echo "         Set the disable expiration time using POSIX time format instead."
    echo
    echo "      -f"
    echo "      --force"
@@ -260,6 +332,8 @@ if [ ! "${EUID}" = "0" ]; then
    echo "You need root privileges to run $0"
    exit 1
 fi
+
+log "Running with: $*"
 
 case "$1" in
    'enable')
